encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:query>", views.display, name="result"),
    path("newpage", views.new, name="newpage"),
    path("wiki/<str:query>/edit", views.edit, name="edit"),
    path("random", views.random, name="random")

]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import markdown2 # Convert markdown text to html
from random import choice # Generate random numbers

#from django import forms
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect

from . import util


def index(request):
 
    # Post: searchbar
    if request.method == "POST":
        query = request.POST.get('q')
        
        # Check if query doesn't exist
        if query not in util.list_entries():

            # Check for substring
            results=[]
            for entry in util.list_entries():
                if entry.find(query) != -1:
                    results.append(entry)
            # Display results if found:
            if len(results) != 0:
                return render(request, f"encyclopedia/results.html", {
                    "results": results
                })

            # Display an error if no substring is found
            return render(request, f"encyclopedia/notfound.html", {
                "query": query
            })
        
        # If query exists, redirect to display
        return HttpResponseRedirect(reverse("encyclopedia:result", kwargs={'query':query}))
    
    # Get    
    else: 
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
        })

def display(request, query):
    
    # Post: edit 
    if request.method == "POST":
          
        # Save markdown file
        text = request.POST.get('text')
        f = open(f'entries/{query}.md', 'w')
        f.write(text)
        f.close()

        # Write html file
        md = util.get_entry(query) # Get md text
        html = markdown2.markdown(md) # Convert to html
        
        f = open(f'encyclopedia/templates/encyclopedia/{query}.html', 'w') # Write file
        f.write("""{% extends "encyclopedia/layout.html" %} {% block title %}{{query}}{% endblock %}{% block body %}""")
        f.write(html)
        f.write(f"""<a href="{query}/edit">Edit</a>""")
        f.write("""{% endblock %}""")
        f.close()

        return render(request, f"encyclopedia/{query}.html")
    
    # Get
    # Display an error if not found
    if query not in util.list_entries():
        return render(request, f"encyclopedia/notfound.html", {
            "query": query
        })

    # If found display page
    entry = util.get_entry(query) # Get md content
    html = markdown2.markdown(entry) # Convert md to html

    # Write html file
    f = open(f'encyclopedia/templates/encyclopedia/{query}.html', 'w') # Open file to write content
    f.write("""{% extends "encyclopedia/layout.html" %} {% block title %}{{query}}{% endblock %}{% block body %}""")
    f.write(html)
    f.write(f"""<a href="{query}/edit">Edit</a>""")
    f.write("""{% endblock %}""")
    f.close()

    # Display result
    return render(request, f"encyclopedia/{query}.html", {
        "entry": util.get_entry(query),
        "query": query
    })

def new(request):

    # Post: add new entry
    if request.method == "POST":
        entry = request.POST.get('title')

        # If entry exists, render an error
        if entry in util.list_entries():  
            return render(request, f"encyclopedia/exists.html",{
                "entry": entry
            })      

        # If not, add entry
        text = request.POST.get('text') # Get text

        # Write markdown content
        f = open(f'entries/{entry}.md', 'w')
        f.write(f"# {entry}\n\n")
        f.write(text)
        f.close()

    # Get 
    # Display New Page 
    return render(request, "encyclopedia/newpage.html")

def edit(request, query):
    # Get
    text = util.get_entry(query) # Get markdown text

    # Render edit page with actual title and text 
    return render(request, "encyclopedia/edit.html", {
        "entry": query,
        "text": text,
    })

def random(request):
    # Retrieve list of entries
    list = util.list_entries()
    # Select one randomly
    random = choice(list)
    # Return random page
    return HttpResponseRedirect(reverse("encyclopedia:result", kwargs={'query':random}))

encyclopedia/templates/encyclopedia/CSS.html
{% extends "encyclopedia/layout.html" %} {% block title %}{{query}}{% endblock %}{% block body %}<h1>CSS</h1>

<p>CSS is a language that can be used to add style to an <a href="/wiki/HTML">HTML</a> page.</p>
<a href="CSS/edit">Edit</a>{% endblock %}

encyclopedia/templates/encyclopedia/Cat.html
{% extends "encyclopedia/layout.html" %} {% block title %}{{query}}{% endblock %}{% block body %}<h1>Cat</h1>

<p>A little animal.</p>
<a href="Cat/edit">Edit</a>{% endblock %}

encyclopedia/templates/encyclopedia/Cow.html
{% extends "encyclopedia/layout.html" %} {% block title %}{{query}}{% endblock %}{% block body %}<h1>Cow</h1>

<p>Fat animal.</p>
<a href="Cow/edit">Edit</a>{% endblock %}

encyclopedia/templates/encyclopedia/Django.html
{% extends "encyclopedia/layout.html" %} {% block title %}{{query}}{% endblock %}{% block body %}<h1>Django</h1>

<p>Django is a web framework written using <a href="/wiki/Python">Python</a> that allows for the design of web applications that generate <a href="/wiki/HTML">HTML</a> dynamically.</p>
<a href="Django/edit">Edit</a>{% endblock %}

encyclopedia/templates/encyclopedia/Dog.html
{% extends "encyclopedia/layout.html" %} {% block title %}{{query}}{% endblock %}{% block body %}<h1>Dog</h1>

<p>The dog (Canis familiaris when considered a distinct species or Canis lupus familiaris when considered a subspecies of the wolf). </p>
<a href="Dog/edit">Edit</a>{% endblock %}

encyclopedia/templates/encyclopedia/Git.html
{% extends "encyclopedia/layout.html" %} {% block title %}{{query}}{% endblock %}{% block body %}<h1>Git</h1>

<p>Git is a version control tool that can be used to keep track of versions of a software project.</p>

<h2>GitHub</h2>

<p>GitHub is an online service for hosting git repositories.</p>
<a href="Git/edit">Edit</a>{% endblock %}

encyclopedia/templates/encyclopedia/HTML.html
{% extends "encyclopedia/layout.html" %} {% block title %}{{query}}{% endblock %}{% block body %}<h1>HTML</h1>

<p>HTML is a markup language that can be used to define the structure of a web page. HTML elements include</p>

<ul>
<li>headings</li>
<li>paragraphs</li>
<li>lists</li>
<li>links</li>
<li>and more!</li>
</ul>

<p>The most recent major version of HTML is HTML5.</p>
<a href="HTML/edit">Edit</a>{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}
    <h1>Create new page :</h1>

    <form action="{% url 'encyclopedia:result' entry %}" method="post">
        {% csrf_token %}
        <input disabled style="width:80%" type="text" name="title" placeholder="{{entry}}" >
        <br></br>
        <label for="text">Enter text here:</label>
        <p></p>
        <textarea id="text" name="text" rows="1" cols="30">{{text}}</textarea>
        <br></br>
        <input style="margin-left:75%" type="submit" value="Save">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="wiki/{{entry}}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
    <h1>Create new page :</h1>

    <form action="" method="post">
        {% csrf_token %}
        <input style="width:80%;" type="text" name="title" placeholder="Enter title here" >
        <br></br>
        <label for="text">Enter text here:</label>
        <p></p>
        <textarea style="resize:none" id="text" name="text" rows="1" cols="30"></textarea>
        <br></br>
        <input style="margin-left:75%" type="submit" value="Save">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/notfound.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}

    <h5>The page "{{query}}" does not exist.</h5>

{% endblock %}

encyclopedia/templates/encyclopedia/python.html
{% extends "encyclopedia/layout.html" %} {% block title %}{{query}}{% endblock %}{% block body %}<h1>Python</h1>

<p>Python is a programming language that can be used both for writing <strong>command-line scripts</strong> or building <strong>web applications</strong>.</p>
<a href="Python/edit">Edit</a>{% endblock %}

encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Results
{% endblock %}

{% block body %}
    <h1>Did you mean:</h1>

    <ul>
        {% for result in results %}
            <a href="wiki/{{result}}"><li>{{ result }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}